export const ADD_PROJECT = "ADD_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const SET_PROJECT_TASK = "SET_PROJECT_TASK";

// type for users

export const GET_USER_LOGED = "GET_USER_LOGED";
export const DELETE_USER_AUTH = "DELETE_USER_AUTH";
export const GET_USER_PROJECT = "GET_USER_PROJECT";
export const SET_PROJECT_USER = "SET_PROJECT_USER";

export const DELETE_PROJECT_USER = "DELETE_PROJECT_USER";

export const GET_PROJECT_TASK = "GET_PROJECT_TASK";

// action para editar

export const GET_TASK_TO_EDIT = "GET_TASK_TO_EDIT";
export const DELETE_TASK_TO_EDIT = "DELETE_TASK_TO_EDIT";

export const STATUS_DELETE = "STATUS_DELETE";
export const SET_TASK_TO_EDIT = "SET_TASK_TO_EDIT";
export const SET_STATUS_TO_EDIT = "SET_STATUS_TO_EDIT";

export const DELETE_PROJECT_FIREBASE = "DELETE_PROJECT_FIREBASE";
export const SET_IMAGE_URL = "SET_IMAGE_URL";
